CREATE TABLE `lit` (`id` INT(255) NOT NULL AUTO_INCREMENT PRIMARY KEY, `patient` TEXT(255) NOT NULL, `letter` VARCHAR(1) NOT NULL, `surveillance` BOOLEAN NOT NULL DEFAULT FALSE) ENGINE = InnoDB;
DROP TABLE `lit`;
CREATE TABLE `lit` (`patient` TEXT NOT NULL, `letter` VARCHAR(1) NOT NULL PRIMARY KEY, `surveillance` BOOLEAN NOT NULL DEFAULT FALSE) ENGINE = InnoDB;
CREATE TABLE `lit_message` (`id` TEXT NOT NULL) ENGINE = InnoDB;