CREATE TABLE organ (
    id INT(255) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    type VARCHAR(255) NOT NULL,
    side VARCHAR(255) NOT NULL,
    date DATE NOT NULL,
    valid BOOLEAN NOT NULL DEFAULT FALSE,
);